export const currentTechologies = [
    {id: 1, name: 'HTML5', imgT: '/img/technologies/html5.png', alt: 'HTML5 Image', project: [14,15] },
    {id: 2, name: 'CSS3', imgT: '/img/technologies/css3.png', alt: 'CSS3 Image', project: [2,3,6,7,8,14,15] },
    {id: 3, name: 'JavaScript', imgT: '/img/technologies/js.png', alt: 'JavaScript Image', project: [14,15] },
    {id: 4, name: 'React.js ', imgT: '/img/technologies/react-js.png', alt: 'React.js Image', project: [3,4,5,6,7,8,9,10,11,12] },
    {id: 5, name: 'Next.js', imgT: '/img/technologies/next-js.png', alt: 'Next.js Image', project: [1,2] },
    {id: 6, name: 'MongoDB', imgT: '/img/technologies/mongodb.png', alt: 'MongoDB Image', project: [12] },
    {id: 7, name: 'Material-UI', imgT: '/img/technologies/mui.png', alt: 'Material-UI Image', project: [10] },
    {id: 8, name: 'Express.js', imgT: '/img/technologies/express-js.png', alt: 'Express.js Image', project: [12] },
    {id: 9, name: 'Node.js', imgT: '/img/technologies/node-js.png', alt: 'Node.js Image', project: [12] },
    {id: 10, name: 'PHP', imgT: '/img/technologies/php.png', alt: 'PHP Image', project: [14,15] },
    {id: 11, name: 'Prisma', imgT: '/img/technologies/prisma.png', alt: 'Prisma Image', project: [1] },
    {id: 12, name: 'React Bootstrap', imgT: '/img/technologies/react-bootstrap.png', alt: 'React Bootstrap Image', project: [5] },
    {id: 13, name: 'Sass', imgT: '/img/technologies/sass.png', alt: 'Sass Image', project: [14,15] },
    {id: 14, name: 'Socket.io', imgT: '/img/technologies/socket.io.png', alt: 'Socket.io Image', project: [12] },
    {id: 15, name: 'SQL', imgT: '/img/technologies/sql.png', alt: 'SQL Image', project: [14,15] },
    {id: 16, name: 'Strapi', imgT: '/img/technologies/strapi.png', alt: 'Strapi Image', project: [2] },
    {id: 17, name: 'TailwindCss', imgT: '/img/technologies/tailwind-css.png', alt: 'TailwindCss Image', project: [1,4,9,11,12] },
    {id: 18, name: 'Wordpress', imgT: '/img/technologies/wordpress.png', alt: 'Wordpress Image', project: [13] },
    ];